<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="16653" started-at="2018-06-14T12:12:02Z" finished-at="2018-06-14T12:12:19Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="16653" started-at="2018-06-14T12:12:02Z" finished-at="2018-06-14T12:12:19Z">
      <class name="testscript.FirstTest">
        <test-method status="PASS" signature="launch()[pri:0, instance:testscript.FirstTest@6d4b1c02]" name="launch" is-config="true" duration-ms="14007" started-at="2018-06-14T17:42:02Z" finished-at="2018-06-14T17:42:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launch -->
        <test-method status="PASS" signature="initializePage()[pri:0, instance:testscript.FirstTest@6d4b1c02]" name="initializePage" is-config="true" duration-ms="21" started-at="2018-06-14T17:42:16Z" finished-at="2018-06-14T17:42:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initializePage -->
        <test-method status="FAIL" signature="firstTest()[pri:0, instance:testscript.FirstTest@6d4b1c02]" name="firstTest" duration-ms="2054" started-at="2018-06-14T17:42:16Z" finished-at="2018-06-14T17:42:18Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [xasxa] but found [xasx]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [xasxa] but found [xasx]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at testscript.FirstTest.firstTest(FirstTest.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- firstTest -->
        <test-method status="PASS" signature="screenshot(org.testng.ITestResult)[pri:0, instance:testscript.FirstTest@6d4b1c02]" name="screenshot" is-config="true" duration-ms="387" started-at="2018-06-14T17:42:18Z" finished-at="2018-06-14T17:42:19Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=firstTest status=FAILURE method=FirstTest.firstTest()[pri:0, instance:testscript.FirstTest@6d4b1c02] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- screenshot -->
        <test-method status="PASS" signature="crash()[pri:0, instance:testscript.FirstTest@6d4b1c02]" name="crash" is-config="true" duration-ms="162" started-at="2018-06-14T17:42:19Z" finished-at="2018-06-14T17:42:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- crash -->
      </class> <!-- testscript.FirstTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
